name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: |
        npm i
        npm i vsce
        npx vsce package
    - name: Get short sha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sourcepawn-vscode-${{ steps.vars.outputs.sha_short }}.vsix
        path: |
          *.vsix
